language: cpp
sudo: required
dist: trusty

env:
  global:
    - SAMP_SERVER_ROOT=$TRAVIS_BUILD_DIR/samp03
    - PATH=$TRAVIS_BUILD_DIR/samp-server-cli:$PATH
  matrix:
    - STATIC_BUILD=ON BUILD_TYPE=Release
    - STATIC_BUILD=ON BUILD_TYPE=Debug
    - STATIC_BUILD=OFF BUILD_TYPE=Release
    - STATIC_BUILD=OFF BUILD_TYPE=Debug

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - cmake
    - g++-multilib

cache:
  directories:
    - boost_1_57_0
    - mysql-connector-c-6.1.6-src

before_install:
  - if [ ! -f "mysql-connector-c-6.1.6-src/CMakeLists.txt" ]; then wget "http://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.6-src.tar.gz"; fi
  - if [ ! -f "mysql-connector-c-6.1.6-src/CMakeLists.txt" ]; then tar xzf mysql-connector-c-6.1.6-src.tar.gz; fi
  
  - if [ ! -f "boost_1_57_0/bootstrap.sh" ]; then wget "http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz"; fi
  - if [ ! -f "boost_1_57_0/bootstrap.sh" ]; then tar xzf boost_1_57_0.tar.gz; fi
  
  - wget http://files.sa-mp.com/samp037svr_R2-1.tar.gz
  - tar xzf samp037svr_R2-1.tar.gz
  
  - wget http://files.sa-mp.com/samp037_svr_R2-1-1_win32.zip
  - unzip samp037_svr_R2-1-1_win32.zip -d $SAMP_SERVER_ROOT pawno/include/*
  
  - git clone https://github.com/Zeex/samp-server-cli.git
  
  - wget https://github.com/Zeex/pawn/releases/download/20150531/pawnc-3.10.20150531-linux.tar.gz
  - sudo tar xvf pawnc-3.10.20150531-linux.tar.gz --strip-components=1 -C /usr/local
  - sudo ldconfig

install:
  - cd mysql-connector-c-6.1.6-src/
  - cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_LAYOUT=DEB > /dev/null
  - make -j2 > /dev/null
  - sudo make install > /dev/null
  - cd ..
  
  - cd boost_1_57_0/
  - if [ ! -f "b2" ]; then sudo bash bootstrap.sh --prefix=/usr/local --with-libraries=system,chrono,thread,date_time,atomic; fi
  - sudo ./b2 variant=${BUILD_TYPE,,} link=static threading=multi address-model=32 runtime-link=shared -j2 -d0 install
  - cd ..
  - sudo ldconfig

before_script:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS test;"
  - cmake . -DCMAKE_INSTALL_PREFIX=${SAMP_SERVER_ROOT} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_TESTS=ON -DBUILD_STATIC=${STATIC_BUILD}

script:
  - make -j2
  - make install
  # tests
  - pawncc tests/unit_test.pwn -d3 -Z+ -\; -\( -i${SAMP_SERVER_ROOT}/pawno/include -itests/include -ounit_test
  - cp -R tests/test_data/* ${SAMP_SERVER_ROOT}
  - cp *.amx ${SAMP_SERVER_ROOT}/gamemodes
  - samp-server-cli -o -g unit_test -d mysql.so -T 60

after_script: cat ${SAMP_SERVER_ROOT}/logs/plugins/mysql.log

before_cache:
  - rm -f boost_1_57_0/bin.v2/config.log
  - rm -f mysql-connector-c-6.1.6-src/Docs/INFO_BIN
